services:
  backend:
    build: ./backend
    container_name: book-backend
    ports:
      - "8080:8080"
    env_file:
      - .env.pro
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: book-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.pro
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: book-db
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
